trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'HelloWorld'


- task: Bash@3
  displayName: 'Create App Configuration file'
  inputs:
    targetType: 'inline'
    script: |
      cd $(Build.ArtifactStagingDirectory)
      touch appconfigurationConfig.json
      echo '{' > appconfigurationConfig.json
      echo '  "smtp_port": "'"$(Smtp__Port)"'",' >> appconfigurationConfig.json
      echo '  "smtp_host": "'"$(Smtp__Host)"'",' >> appconfigurationConfig.json
      echo '  "MY_VAR_3": "'"MY_VAR_3"'",' >> appconfigurationConfig.json
      echo '  "MY_VAR_4": "'"${MY_VAR_4}"'",' >> appconfigurationConfig.json
      echo '  "MY_VAR_5": "'"${MY_VAR_5}"'"' >> appconfigurationConfig.json
      echo '}' >> appconfigurationConfig.json
      #cat appconfigurationConfig.json
      
      
- task: AzureAppConfigurationPush@5
  inputs:
    azureSubscription: $(subscriptionConnectionProd)
    AppConfigurationEndpoint: 'https://ac-link.azconfig.io'
    ConfigurationFile: '$(Build.ArtifactStagingDirectory)/appconfigurationConfig.json'
    Separator: ','
    Strict: false
  displayName: 'Push configuration to Azure App Configuration'
