# trigger:
# - none

# pool:
#   vmImage: ubuntu-latest

# variables:
#   AgentIP: $[ format('{0}', agent.ipAddresses[0]) ]


# steps:

# - task: AzureCLI@2
#   displayName: 'Get Agent IP address'
#   inputs:
#     azureSubscription: 'ksz-sub-devind-rg'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'echo "##vso[task.setvariable variable=AgentIP;isOutput=true]$(curl -s https://api.ipify.org)"'
# - task: AzureCLI@2
#   displayName: 'AKS Credentials' 
#   inputs:
#     azureSubscription: 'ksz-sub-devind-rg'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks'

# - task: AzureCLI@2
#   displayName: 'AKS new IP range with Agent IP' 
#   inputs:
#     azureSubscription: 'ksz-sub-devind-rg'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az aks update -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24,$(AgentIP)"'

# - task: HelmInstaller@1
#   displayName: 'Install Helm'
#   inputs:
#     helmVersionToInstall: 'latest'

# - task: HelmDeploy@0
#   displayName: 'Helm helloworld deploy' 
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'ksz-sub-devind-rg'
#     azureResourceGroup: 'ksz-d-devind-rg'
#     kubernetesCluster: 'ksz-d-devind-aks'
#     namespace: 'dev'
#     command: 'upgrade'
#     arguments: '--install'
#     chartType: 'FilePath'
#     chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  AgentIP: $[ format('{0}', agent.ipAddresses[0]) ]
  
steps:
- task: AzureCLI@2
  displayName: 'AKS Credentials' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks'

- script: |
    currentIPRanges=$(az aks show -g ksz-d-devind-rg -n ksz-d-devind-aks --query apiServerAuthorizedIpRanges -o tsv)
    updatedIPRanges=$(echo $currentIPRanges $AgentIP | tr ' ' '\n' | sort -u | tr '\n' ' ')
    az aks update -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges $updatedIPRanges --no-wait
  displayName: 'AKS new IP range'

- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  displayName: 'Helm helloworld deploy' 
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'ksz-sub-devind-rg'
    azureResourceGroup: 'ksz-d-devind-rg'
    kubernetesCluster: 'ksz-d-devind-aks'
    namespace: 'dev'
    command: 'upgrade'
    arguments: '--install'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'
