# trigger:
# - none

# pool:
#   vmImage: ubuntu-latest

# steps:

# - task: AzureCLI@2
#   displayName: 'AKS Credentials' 
#   inputs:
#     azureSubscription: 'ksz-sub-devind-rg'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks'

# - task: AzureCLI@2
#   displayName: 'AKS new IP range with Agent IP' 
#   inputs:
#     azureSubscription: 'ksz-sub-devind-rg'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: 'az aks update -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24"'

# - task: HelmInstaller@1
#   displayName: 'Install Helm'
#   inputs:
#     helmVersionToInstall: 'latest'

# - task: HelmDeploy@0
#   displayName: 'Helm helloworld deploy' 
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscription: 'ksz-sub-devind-rg'
#     azureResourceGroup: 'ksz-d-devind-rg'
#     kubernetesCluster: 'ksz-d-devind-aks'
#     namespace: 'dev'
#     command: 'upgrade'
#     arguments: '--install'
#     chartType: 'FilePath'
#     chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureCLI@2
  displayName: 'AKS Credentials' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks'

- task: AzureCLI@2
  displayName: 'AKS new IP range with Agent IP' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get current agent IP
      AGENT_IP=$(curl ifconfig.co)
      
      # Add agent IP to AKS authorized IP ranges
      az rest --method put --uri https://management.azure.com/subscriptions/$(az account show --query id -o tsv)/resourceGroups/ksz-d-devind-rg/providers/Microsoft.ContainerService/managedClusters/ksz-d-devind-aks?api-version=2021-11-01 --body "{\"properties\": {\"apiServerAuthorizedIpRanges\": [\"188.117.157.0/24\", \"$AGENT_IP\"]}}"
      
      # Set output variable for agent IP
      echo "##vso[task.setvariable variable=AGENT_IP]$AGENT_IP"

- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: 'latest'

- task: HelmDeploy@0
  displayName: 'Helm helloworld deploy' 
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'ksz-sub-devind-rg'
    azureResourceGroup: 'ksz-d-devind-rg'
    kubernetesCluster: 'ksz-d-devind-aks'
    namespace: 'dev'
    command: 'upgrade'
    arguments: '--install'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'

- task: AzureCLI@2
  displayName: 'AKS remove agent IP from IP ranges' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get current authorized IP ranges for AKS
      AUTHORIZED_IP_RANGES=$(az aks show -g ksz-d-devind-rg -n ksz-d-dev
