# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: HelmDeploy@0
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'ksz-sub-devind-rg'
    azureResourceGroup: 'ksz-d-devind-rg'
    kubernetesCluster: 'ksz-d-devind-aks'
    namespace: 'dev'
    command: 'install'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'