trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: 'AKS - IP range'
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      Current_IP=$(curl ipinfo.io/ip)
      echo $Current_IP
      Current_IPO="${Current_IP%.*}.0"
      echo $Current_IPO
      echo "az aks update -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24,95.215.28.0/24,$Current_IPO/24"" > api_ips.sh
      cat api_ips.sh
      chmod +x api_ips.sh
      bash api_ips.sh
- task: AzureCLI@2
  displayName: 'AKS Credentials' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks'

- task: HelmInstaller@1
  displayName: 'Install Helm'
  inputs:
    helmVersionToInstall: 'latest'

- task: AzureCLI@2
  displayName: 'Helm upgrade service' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'helm upgrade --install --namespace dev --wait --force --reuse-values 20230221.12 /home/vsts/work/1/s/helm/helloworld-master/helloworld/'


- task: HelmDeploy@0
  displayName: 'Helm helloworld deploy' 
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'ksz-sub-devind-rg'
    azureResourceGroup: 'ksz-d-devind-rg'
    kubernetesCluster: 'ksz-d-devind-aks'
    namespace: 'dev'
    command: 'upgrade'
    arguments: '--install --force'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'

- task: AzureCLI@2
  displayName: 'AKS Update to old IP range' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az aks update -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24,95.215.28.0/24"'
