trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: AzureCLI@2
  displayName: 'AKS Credentials and new IP range' 
  inputs:
    azureSubscription: 'ksz-sub-devind-rg'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks
      az aks create -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24" --generate-ssh-keys --output none
      az aks ssh-key show -g ksz-d-devind-rg -n ksz-d-devind-aks --name id_rsa --query "publicKey" -o tsv > $(ssh-keygen -y -f ~/.ssh/id_rsa)      
    
    #inlineScript: 'az aks get-credentials -g ksz-d-devind-rg -n ksz-d-devind-aks && az aks create -g ksz-d-devind-rg -n ksz-d-devind-aks --api-server-authorized-ip-ranges "188.117.157.0/24" --generate-ssh-keys'
    #apiVersion: '2022-09-02-preview'

- task: HelmDeploy@0
  displayName: 'Helm helloworld deploy' 
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'ksz-sub-devind-rg'
    azureResourceGroup: 'ksz-d-devind-rg'
    kubernetesCluster: 'ksz-d-devind-aks'
    namespace: 'dev'
    command: 'upgrade'
    arguments: '--install'
    chartType: 'FilePath'
    chartPath: '$(System.DefaultWorkingDirectory)/helm/helloworld-master/helloworld/'
