trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'HelloWorld'

- task: AzureKeyVault@2
  inputs:
    azureSubscription: $(subscriptionConnectionProd)
    KeyVaultName: $(keyvaultName)
    secretsFilter: '*'
  displayName: 'Connect do KeyVault'

- task: AzureCLI@2
  displayName: 'Pętla'
  inputs:
    azureSubscription: $(subscriptionConnectionProd)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      i=1
      n=$(env | grep myValue | wc -l)
      while [ $i -le $n ]
      do
        envVar="myValue$i"
        secretVar="mySecretName$i"
        secretName="${!secretVar}"
        az keyvault secret set --vault-name $keyvaultName --name $secretName --value ${!envVar}
        i=$((i+1))
      done
  env:
    keyvaultName: $(keyvaultName)

    myValue1: 'wartosc1'
    mySecretName1: 'mySecret1'

    myValue2: 'wartosc2'
    mySecretName2: 'mySecret2'

    myValue3: 'wartosc3'
    mySecretName3: 'mySecret3'

    myValue4: 'wartosc4'
    mySecretName4: 'mySecret4'